/**
 * Channel configuration constants
 * Organized by feature/domain
 */
import { IPC_EVENTS } from "@common/ipc-events";

// Git repository send channels
export const GIT_SEND_CHANNELS = [
  IPC_EVENTS.REPO.OPEN,
  IPC_EVENTS.REPO.INIT,
  IPC_EVENTS.REPO.BROWSE,
  IPC_EVENTS.REPO.INIT_BROWSE,
  IPC_EVENTS.REPO.CLOSE,
  IPC_EVENTS.REPO.FETCH,
  IPC_EVENTS.REPO.SET_CRED,
  IPC_EVENTS.REPO.PULL,
  IPC_EVENTS.REPO.PUSH,
  IPC_EVENTS.REPO.GET_COMMIT,
  IPC_EVENTS.REPO.STAGE,
  IPC_EVENTS.REPO.UNSTAGE,
  IPC_EVENTS.REPO.STAGE_LINES,
  IPC_EVENTS.REPO.UNSTAGE_LINES,
  IPC_EVENTS.REPO.COMMIT_STAGED,
  IPC_EVENTS.REPO.COMMIT,
  IPC_EVENTS.REPO.STASH,
  IPC_EVENTS.REPO.POP,
  IPC_EVENTS.REPO.APPLY,
  IPC_EVENTS.REPO.CREATE_BRANCH,
  IPC_EVENTS.REPO.CHECKOUT,
  IPC_EVENTS.REPO.DISCARD_ALL,
  IPC_EVENTS.REPO.RESET_HARD,
  IPC_EVENTS.REPO.RESET_SOFT,
  IPC_EVENTS.REPO.DELETE_STASH,
  IPC_EVENTS.REPO.CREATE_TAG,
  IPC_EVENTS.REPO.DELETE_TAG,
  IPC_EVENTS.REPO.DELETE_BRANCH,
  IPC_EVENTS.REPO.PUSH_TAG,
  IPC_EVENTS.REPO.REMOVE_HISTORY,
];

// Infrastructure send channels
export const INFRASTRUCTURE_SEND_CHANNELS = [
  IPC_EVENTS.SHELL.OPEN,
  IPC_EVENTS.SECURE.CLEAR_CACHE,
  IPC_EVENTS.UPDATER.CHECK,
  IPC_EVENTS.SETTINGS.INIT,
  IPC_EVENTS.SETTINGS.SET,
  IPC_EVENTS.SETTINGS.SET_SECURE_REPO,
  IPC_EVENTS.SETTINGS.GET_SECURE_REPO,
  IPC_EVENTS.SETTINGS.BROWSE_FILE,
];

// CI send channels
export const CI_SEND_CHANNELS = [IPC_EVENTS.CI.REPO_CHANGED];

// JIRA send channels
export const JIRA_SEND_CHANNELS = [
  IPC_EVENTS.JIRA.GET_PROJECTS,
  IPC_EVENTS.JIRA.GET_ISSUES,
  IPC_EVENTS.JIRA.GET_ISSUE,
  IPC_EVENTS.JIRA.UPDATE_ISSUE_LEGACY,
  IPC_EVENTS.JIRA.ADD_COMMENT,
];

// Legacy send channels
export const LEGACY_SEND_CHANNELS = [
  "git-command",
  "settings-change",
  "jira-action",
];

// Combined send channels
export const VALID_SEND_CHANNELS = Object.freeze([
  ...GIT_SEND_CHANNELS,
  ...INFRASTRUCTURE_SEND_CHANNELS,
  ...CI_SEND_CHANNELS,
  ...JIRA_SEND_CHANNELS,
  ...LEGACY_SEND_CHANNELS,
]);

// Invoke channels
export const VALID_INVOKE_CHANNELS = [
  "shell:openExternal",
  "git:execute",
  "settings:get",
  "settings:set",
  "repo:get",
  "repo:open",
  "repo:commits",
  "secure:getPassword",
  "secure:setPassword",
  "ci:status",
  "jira:issues",
  "file:open",
];

// Git receive channels
export const GIT_RECEIVE_CHANNELS = [
  IPC_EVENTS.REPO.OPEN_SUCCESSFUL,
  IPC_EVENTS.REPO.OPEN_FAILED,
  IPC_EVENTS.REPO.CLOSED,
  IPC_EVENTS.REPO.CURRENT_REMOVED,
  IPC_EVENTS.REPO.COMMITS_UPDATED,
  IPC_EVENTS.REPO.REF_RETRIEVED,
  IPC_EVENTS.REPO.BRANCH_CHANGED,
  IPC_EVENTS.REPO.BRANCH_POSITION_RETRIEVED,
  IPC_EVENTS.REPO.REMOTES_CHANGED,
  IPC_EVENTS.REPO.FILE_STATUS_RETRIEVED,
  IPC_EVENTS.REPO.CREDENTIAL_ISSUE,
  IPC_EVENTS.REPO.PULLED,
  IPC_EVENTS.REPO.PULL_FAILED,
  IPC_EVENTS.REPO.PUSHED,
  IPC_EVENTS.REPO.PUSH_FAILED,
  IPC_EVENTS.REPO.FETCHED,
  IPC_EVENTS.REPO.FETCH_FAILED,
  IPC_EVENTS.REPO.COMMIT_DETAIL_RETRIEVED,
  IPC_EVENTS.REPO.COMMITTED,
  IPC_EVENTS.REPO.STASHED,
  IPC_EVENTS.REPO.POPPED,
  IPC_EVENTS.REPO.APPLIED,
  IPC_EVENTS.REPO.BRANCH_CREATED,
  IPC_EVENTS.REPO.BRANCH_CREATE_FAILED,
  IPC_EVENTS.REPO.CHECKEDOUT,
  IPC_EVENTS.REPO.DISCARDED,
  IPC_EVENTS.REPO.RESETTED,
  IPC_EVENTS.REPO.STASH_DELETED,
  IPC_EVENTS.REPO.TAG_CREATED,
  IPC_EVENTS.REPO.TAG_DELETED,
  IPC_EVENTS.REPO.BRANCH_DELETED,
  IPC_EVENTS.REPO.TAG_PUSHED,
  IPC_EVENTS.REPO.BLOCKING_OPERATION_BEGAN,
  IPC_EVENTS.REPO.BLOCKING_OPERATION_END,
  IPC_EVENTS.REPO.BLOCKING_UPDATE,
  IPC_EVENTS.REPO.FOLDER_SELECTED,
  IPC_EVENTS.REPO.INIT_PATH_SELECTED,
  IPC_EVENTS.REPO.INIT_SUCCESSFUL,
  IPC_EVENTS.REPO.INIT_FAILED,
  IPC_EVENTS.REPO.USERNAME_RETRIEVED,
  IPC_EVENTS.REPO.PASSWORD_RETRIEVED,
];

// Settings receive channels
export const SETTINGS_RECEIVE_CHANNELS = [
  IPC_EVENTS.SETTINGS.EFFECTIVE_UPDATED,
  IPC_EVENTS.SETTINGS.SECURE_REPO_RETRIEVED,
  IPC_EVENTS.SETTINGS.FOLDER_SELECTED,
];

// Other receive channels
export const OTHER_RECEIVE_CHANNELS = [
  IPC_EVENTS.AUTO_FETCH.TIMEOUT,
  IPC_EVENTS.UPDATER.UPDATE_AVAILABLE,
  IPC_EVENTS.UPDATER.UPDATE_NOT_AVAILABLE,
  IPC_EVENTS.UPDATER.DOWNLOADED,
  IPC_EVENTS.CI.APPVEYOR.STATUS_RETRIEVED,
  IPC_EVENTS.JIRA.PROJECTS_RETRIEVED,
  IPC_EVENTS.JIRA.ISSUES_RETRIEVED,
  IPC_EVENTS.JIRA.ISSUE_RETRIEVED,
  IPC_EVENTS.JIRA.ISSUE_UPDATED,
  IPC_EVENTS.JIRA.COMMENT_ADDED,
];

// Legacy receive channels
export const LEGACY_RECEIVE_CHANNELS = [
  "repo:updated",
  "settings:changed",
  "ci:statusChanged",
  "jira:issueUpdated",
];

// Combined receive channels
export const VALID_RECEIVE_CHANNELS = Object.freeze([
  ...GIT_RECEIVE_CHANNELS,
  ...SETTINGS_RECEIVE_CHANNELS,
  ...OTHER_RECEIVE_CHANNELS,
  ...LEGACY_RECEIVE_CHANNELS,
]);
